# Generated by Django 2.1.3 on 2019-02-19 05:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='uid',
            field=models.CharField(default=uuid.UUID('83f896aa-965a-40df-99b4-75f8d0864afe'), max_length=40),
        ),
    ]
